package de.euler.task2

class Task2{
//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

  def solve : Int = {
    return solveRec(1,1)
  }
  
  def solveRec(fib1:Int, fib2:Int): Int = {
    if (fib2 >= 4000000) return 0
    return (if (fib2 % 2 == 0) fib2 else 0) + solveRec(fib2, fib1+fib2) 
  }
  
}